### ISSUE TITLE
Не работает автодействие по истечению таймера атаки Хищного Растения (потенциальное зависание игры)

### ISSUE THREAD

**Issue by evoguest** [ivan-work/evolution-web#110]
```
phase: feeding
plants: PlantCarn +++++, PlantCarn +++++, PlantCarn +++++, Fungus +++++ PlantTraitOfficinalis, Fungus +++++ 
players:
  - continent: mass tail carn, mass tail carn, mass tail, tail, fat tail
  - continent: mass tail carn, mass tail carn, mass tail cni, tail, fat tail
settings:
  addon_plantarium: true
  timeTurn: 30000
  timeTraitResponse: 15000
```
