### ISSUE TITLE
Иконка отравления хищного растения

### ISSUE THREAD

**Issue by evoguest** [ivan-work/evolution-web#117]
Необходимо приделать к хищному растению иконку "отравился", если оно съедает ядовитое животное и должно умереть в конце фазы, независимо от количества еды на нем.
Сейчас игрокам трудно отследить какое растение когда отравилось.
```
deckPlants: 2 eph
deck: 10 pois
phase: feeding
players:
  - continent: pois, pois
settings:
  addon_plantarium: true
phase: deploy
plants: PlantCarn +, PlantCarn ++, PlantCarn +++, PlantCarn ++++
```
